MARC_COUNTRY_MAP = {
    "af": "Afghanistan",
    "alu": "United States",
    "aku": "United States",
    "aa": "Albania",
    "abc": "Canada",
    "ae": "Algeria",
    "as": "American Samoa",
    "an": "Andorra",
    "ao": "Angola",
    "am": "Anguilla",
    "ay": "Antarctica",
    "aq": "Antigua and Barbuda",
    "ag": "Argentina",
    "azu": "United States",
    "aru": "United States",
    "ai": "Armenia (Republic)",
    "aw": "Aruba",
    "at": "Australia",
    "aca": "Australia",
    "au": "Austria",
    "aj": "Azerbaijan",
    "bf": "Bahamas",
    "ba": "Bahrain",
    "bg": "Bangladesh",
    "bb": "Barbados",
    "bw": "Belarus",
    "be": "Belgium",
    "bh": "Belize",
    "dm": "Benin",
    "bm": "Bermuda Islands",
    "bt": "Bhutan",
    "bo": "Bolivia",
    "bn": "Bosnia and Herzegovina",
    "bs": "Botswana",
    "bv": "Bouvet Island",
    "bl": "Brazil",
    "bcc": "Canada",
    "bi": "British Indian Ocean Territory",
    "vb": "British Virgin Islands",
    "bx": "Brunei",
    "bu": "Bulgaria",
    "uv": "Burkina Faso",
    "br": "Burma",
    "bd": "Burundi",
    "cau": "United States",
    "cb": "Cambodia",
    "cm": "Cameroon",
    "xxc": "Canada",
    "cv": "Cabo Verde",
    "ca": "Caribbean Netherlands",
    "cj": "Cayman Islands",
    "cx": "Central African Republic",
    "cd": "Chad",
    "cl": "Chile",
    "cc": "China",
    "ch": "China (Republic : 1949- )",
    "xa": "Christmas Island (Indian Ocean)",
    "xb": "Cocos (Keeling) Islands",
    "ck": "Colombia",
    "cou": "United States",
    "cq": "Comoros",
    "cf": "Congo (Brazzaville)",
    "cg": "Congo (Democratic Republic)",
    "ctu": "United States",
    "cw": "Cook Islands",
    "xga": "Australia",
    "cr": "Costa Rica",
    "iv": "Côte d'Ivoire",
    "ci": "Croatia",
    "cu": "Cuba",
    "co": "Curaçao",
    "cy": "Cyprus",
    "xr": "Czech Republic",
    "deu": "United States",
    "dk": "Denmark",
    "dcu": "United States",
    "ft": "Djibouti",
    "dq": "Dominica",
    "dr": "Dominican Republic",
    "ec": "Ecuador",
    "ua": "Egypt",
    "es": "El Salvador",
    "enk": "England",
    "eg": "Equatorial Guinea",
    "ea": "Eritrea",
    "er": "Estonia",
    "sq": "Eswatini",
    "et": "Ethiopia",
    "fk": "Falkland Islands",
    "fa": "Faroe Islands",
    "fj": "Fiji",
    "fi": "Finland",
    "flu": "United States",
    "fr": "France",
    "fg": "French Guiana",
    "fp": "French Polynesia",
    "go": "Gabon",
    "gm": "Gambia",
    "gz": "Gaza Strip",
    "gau": "United States",
    "gs": "Georgia (Republic)",
    "gw": "Germany",
    "gh": "Ghana",
    "gi": "Gibraltar",
    "gr": "Greece",
    "gl": "Greenland",
    "gd": "Grenada",
    "gp": "Guadeloupe",
    "gu": "Guam",
    "gt": "Guatemala",
    "gg": "Guernsey",
    "gv": "Guinea",
    "pg": "Guinea-Bissau",
    "gy": "Guyana",
    "ht": "Haiti",
    "hiu": "United States",
    "hm": "Heard and McDonald Islands",
    "ho": "Honduras",
    "hu": "Hungary",
    "ic": "Iceland",
    "idu": "United States",
    "ilu": "United States",
    "ii": "India",
    "inu": "United States",
    "io": "Indonesia",
    "iau": "United States",
    "ir": "Iran",
    "iq": "Iraq",
    "iy": "Iraq-Saudi Arabia Neutral Zone",
    "ie": "Ireland",
    "im": "Isle of Man",
    "is": "Israel",
    "it": "Italy",
    "jm": "Jamaica",
    "ja": "Japan",
    "je": "Jersey",
    "ji": "Johnston Atoll",
    "jo": "Jordan",
    "ksu": "United States",
    "kz": "Kazakhstan",
    "kyu": "United States",
    "ke": "Kenya",
    "gb": "Kiribati",
    "kn": "Korea (North)",
    "ko": "Korea (South)",
    "kv": "Kosovo",
    "ku": "Kuwait",
    "kg": "Kyrgyzstan",
    "ls": "Laos",
    "lv": "Latvia",
    "le": "Lebanon",
    "lo": "Lesotho",
    "lb": "Liberia",
    "ly": "Libya",
    "lh": "Liechtenstein",
    "li": "Lithuania",
    "lau": "United States",
    "lu": "Luxembourg",
    "mg": "Madagascar",
    "meu": "United States",
    "mw": "Malawi",
    "my": "Malaysia",
    "xc": "Maldives",
    "ml": "Mali",
    "mm": "Malta",
    "mbc": "Canada",
    "xe": "Marshall Islands",
    "mq": "Martinique",
    "mdu": "United States",
    "mau": "United States",
    "mu": "Mauritania",
    "mf": "Mauritius",
    "ot": "Mayotte",
    "mx": "Mexico",
    "miu": "United States",
    "fm": "Micronesia (Federated States)",
    "xf": "Midway Islands",
    "mnu": "United States",
    "msu": "United States",
    "mou": "United States",
    "mv": "Moldova",
    "mc": "Monaco",
    "mp": "Mongolia",
    "mtu": "United States",
    "mo": "Montenegro",
    "mj": "Montserrat",
    "mr": "Morocco",
    "mz": "Mozambique",
    "sx": "Namibia",
    "nu": "Nauru",
    "nbu": "United States",
    "np": "Nepal",
    "ne": "Netherlands",
    "nvu": "United States",
    "nkc": "Canada",
    "nl": "New Caledonia",
    "nhu": "United States",
    "nju": "United States",
    "nmu": "United States",
    "xna": "Australia",
    "nyu": "United States",
    "nz": "New Zealand",
    "nfc": "Canada",
    "nq": "Nicaragua",
    "ng": "Niger",
    "nr": "Nigeria",
    "xh": "Niue",
    "xx": "No place, unknown, or undetermined",
    "nx": "Norfolk Island",
    "ncu": "United States",
    "ndu": "United States",
    "xn": "North Macedonia",
    "nik": "Northern Ireland",
    "nw": "Northern Mariana Islands",
    "xoa": "Australia",
    "ntc": "Canada",
    "no": "Norway",
    "nsc": "Canada",
    "nuc": "Canada",
    "ohu": "United States",
    "oku": "United States",
    "mk": "Oman",
    "onc": "Canada",
    "oru": "United States",
    "pk": "Pakistan",
    "pw": "Palau",
    "pn": "Panama",
    "pp": "Papua New Guinea",
    "pf": "Paracel Islands]",
    "py": "Paraguay",
    "pau": "United States",
    "pe": "Peru",
    "ph": "Philippines",
    "pc": "Pitcairn Island",
    "pl": "Poland",
    "po": "Portugal",
    "pic": "Canada",
    "pr": "Puerto Rico",
    "qa": "Qatar",
    "quc": "Canada",
    "qea": "Australia",
    "re": "Réunion",
    "riu": "United States",
    "rm": "Romania",
    "ru": "Russia (Federation)",
    "rw": "Rwanda",
    "sc": "Saint-Barthélemy",
    "xj": "Saint Helena",
    "xd": "Saint Kitts-Nevis",
    "xk": "Saint Lucia",
    "st": "Saint-Martin",
    "xl": "Saint Pierre and Miquelon",
    "xm": "Saint Vincent and the Grenadines",
    "ws": "Samoa",
    "sm": "San Marino",
    "sf": "Sao Tome and Principe",
    "snc": "Canada",
    "su": "Saudi Arabia",
    "stk": "Scotland",
    "sg": "Senegal",
    "rb": "Serbia",
    "se": "Seychelles",
    "sl": "Sierra Leone",
    "si": "Singapore",
    "sn": "Sint Maarten",
    "xo": "Slovakia",
    "xv": "Slovenia",
    "bp": "Solomon Islands",
    "so": "Somalia",
    "sa": "South Africa",
    "xra": "Australia",
    "scu": "United States",
    "sdu": "United States",
    "xs": "South Georgia and the South Sandwich Islands",
    "sd": "South Sudan",
    "sp": "Spain",
    "sh": "Spanish North Africa",
    "xp": "Spratly Island",
    "ce": "Sri Lanka",
    "sj": "Sudan",
    "sr": "Surinam",
    "sw": "Sweden",
    "sz": "Switzerland",
    "sy": "Syria",
    "ta": "Tajikistan",
    "tz": "Tanzania",
    "tma": "Australia",
    "tnu": "United States",
    "fs": "Terres australes et antarctiques françaises",
    "txu": "United States",
    "th": "Thailand",
    "em": "Timor-Leste",
    "tg": "Togo",
    "tl": "Tokelau",
    "to": "Tonga",
    "tr": "Trinidad and Tobago",
    "ti": "Tunisia",
    "tu": "Turkey",
    "tk": "Turkmenistan",
    "tc": "Turks and Caicos Islands",
    "tv": "Tuvalu",
    "ug": "Uganda",
    "un": "Ukraine",
    "ts": "United Arab Emirates",
    "xxk": "United Kingdom",
    "xxu": "United States",
    "uc": "United States Misc. Caribbean Islands",
    "up": "United States Misc. Pacific Islands",
    "uy": "Uruguay",
    "utu": "United States",
    "uz": "Uzbekistan",
    "nn": "Vanuatu",
    "vp": "Various places",
    "vc": "Vatican City",
    "ve": "Venezuela",
    "vtu": "United States",
    "vra": "Australia",
    "vm": "Vietnam",
    "vi": "Virgin Islands of the United States",
    "vau": "United States",
    "wk": "Wake Island",
    "wlk": "Wales",
    "wf": "Wallis and Futuna",
    "wau": "United States",
    "wj": "West Bank of the Jordan River",
    "wvu": "United States",
    "wea": "Australia",
    "ss": "Western Sahara",
    "wiu": "United States",
    "wyu": "United States",
    "ye": "Yemen",
    "ykc": "Canada",
    "za": "Zambia",
    "rh": "Zimbabwe",
}
